

#Fix tmux terminal color issues.
 set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"
#??
 set -g xterm-keys on
 set-option -g focus-events on

#remove lag when pressing esc in vim
set-option -sg escape-time 0

#set prefix
set-option -g prefix C-Space
unbind-key C-b
bind Space send-prefix

# --vim keybinds in terminal.
set-window-option -g mode-keys vi

#color of bottom bar
set -g status on
set -g status-bg black
set -g status-fg white
# set-option -g status-style bg=default


#start window numbers at 1 instead of zero
set -g base-index 1
setw -g pane-base-index 1

#use homerow to select windows
unbind ';'
bind -n M-j select-window -t :1
bind -n M-k select-window -t :2
bind -n M-l select-window -t :3

#vertical and side split bindings
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind S split-window -fv -c "#{pane_current_path}"
bind V split-window -fh -c "#{pane_current_path}"
unbind '"'
unbind %

#have prefix w only list sessions
bind-key -r -T prefix w choose-session
bind-key -r -n 'C-\' resize-pane -Z
# Source .tmux.conf as suggested in `man tmux`
bind -T prefix r source-file ~/.config/tmux/tmux.conf

# vim-like pane resizing  
bind -r i resize-pane -U 2
bind -r u resize-pane -D 2
bind -r o resize-pane -R 2
bind -r y resize-pane -L 2


bind K select-pane -U 
bind J select-pane -D 
bind L select-pane -R 
bind H select-pane -L 

# and now unbind keys
unbind Up     
unbind Down   
unbind Left   
unbind Right  

unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right





bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="F"
bind-key "f" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh switch"
bind-key "N" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh new" 
bind-key "D" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh kill"
bind-key "w" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"
TMUX_FZF_SESSION_FORMAT="#{session_windows} windows"
TMUX_FZF_PREVIEW=0
TMUX_FZF_OPTIONS="-p --reverse --prompt=': ' -w 100% -h 100% -m"
set -g @plugin 'laktak/extrakto'
set -g @extrakto_key "y"
set -g @extrakto_popup_size "50%"
set -g @extrakto_split_direction "v"
set -g @extrakto_split_size "14"
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
 set -g @continuum-restore 'on'
set -g status-right ''
set -g @continuum-save-interval '10'
run '~/.tmux/plugins/tpm/tpm'
